import type { Metadata } from 'next'

import '@/app/layout.scss'
import { bodyFont, headingFont } from './fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={`${bodyFont.variable} ${headingFont.variable}`}>
			<body>{children}</body>
		</html>
	)
}
